services:
  - type: web
    name: chatgpt-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python chatgpt_telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_token_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      - key: WEBHOOK_URL
        value: https://your-app.onrender.com
