services:
  - type: web
    name: chatgpt-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chatgpt_telegram_bot.py"
    envVars:
      - key: PORT
        value: 10000
