services:
  - type: web
    name: chatgpt-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chatgpt_telegram_bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false