services:
  - type: web
    name: chatgpt-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatgpt_telegram_bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: <your-bot-token>
      - key: OPENAI_API_KEY
        value: <your-openai-key>
      - key: WEBHOOK_URL
        value: https://chatgpt-telegram-bot-g6b6.onrender.com
